steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/surnede-cloudrun-app/order-docker-repo/order-service:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/surnede-cloudrun-app/order-docker-repo/order-service:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - order-service
      - --image=us-central1-docker.pkg.dev/surnede-cloudrun-app/order-docker-repo/order-service:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

images:
  - us-central1-docker.pkg.dev/surnede-cloudrun-app/order-docker-repo/order-service:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY

